name: GitHub Actions Demo
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ windows-latest]
        #, ubuntu-latest, macOS-latest]
        dotnet-version: ['5.0']
        #'2.1', '2.2', '3.0', '3.1',
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Hello world action
        with: # Set the secret as an input
          SAUCELABS_ACCESSKEY: ${{ secrets.SAUCELABS_ACCESSKEY }}
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --filter "TestCategory!=LocalOnly&TestCategory!=HeadLess&TestCategory!=SeleniumServer"