name: GitHub Actions Demo
on: 
  push:
    branches:
      - master
  pull_request:

env:
  ResultsDirectory: TestsResults

jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ windows-latest]
        #, ubuntu-latest, macOS-latest]
        dotnet-version: ['5.0']
        #'2.1', '2.2', '3.0', '3.1',
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore

      - name: Build 
        run: dotnet build --configuration Release --no-restore

      - name: Configure Tests
        uses: microsoft/variable-substitution@v1 
        with:
          files: './Selenium.WebDriver.Equip.Tests/bin/Release/net*/SeleniumSettings.config'
        env:
          SeleniumSettings.RemoteBrowserVersion: "91"

      - name: Run Tests
        run: dotnet test -r ${{ env.ResultsDirectory }} -logger:"xunit;Selenium.WebDriver.Equip.Tests.xml" --no-restore --verbosity normal --filter "TestCategory!=LocalOnly&TestCategory!=HeadLess&TestCategory!=SeleniumServer"
        env:
          SAUCELABS_ACCESSKEY: ${{ secrets.SAUCELABS_ACCESSKEY }}
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
      
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: ${{ env.ResultsDirectory }}/Selenium.WebDriver.Equip.Tests.xml