name: Selenium.WebDriver.Equip CI
on: 
  push:
    branches:
      - master
  pull_request:

env:
  ResultsDirectory: TestResults
  EQUIP_ENVIRONMENT : ci

jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest]
        #windows-latest]
        #, ubuntu-latest, macOS-latest]
        dotnet-version: ['5.0']
        #'2.1', '2.2', '3.0', '3.1',
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore Nuget packages
        run: dotnet restore

      - name: Build 
        run: dotnet build --configuration Release --no-restore
#-p:PackageVersion=1.3.141.${{ github.run_number }}
      - name: Run Tests
        run: dotnet test -r ${{ env.ResultsDirectory }} --logger:"nunit;LogFilePath=../../${{ env.ResultsDirectory }}/Selenium.WebDriver.Equip.Tests.Results.xml" --no-restore --verbosity normal --filter "TestCategory!=LocalOnly&TestCategory!=HeadLess&TestCategory!=SeleniumServer"
        env:
          SAUCELABS_ACCESSKEY: ${{ secrets.SAUCELABS_ACCESSKEY }}
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
      
      - name: Publish Nunit Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v1
        if: always()
        with:
          files: Selenium.WebDriver.Equip.Tests.Results.xml